### ISSUE TITLE
Lenke til HF/RHF vises ikke i sykehusprofil hvis man klikker på en tilknyttet enhet

### ISSUE THREAD

**Issue by Stein-Kato** [mong/mongts#2822]

**Comment by Stein-Kato** [comment]
@jo-inge-arnes Kan man kalle denne når man initialiserer `FilterMenu`-komponenten? 

https://github.com/mong/mongts/blob/59aaa29e2aacc52e1823c559e41aa85d7fccb92d/apps/skde/pages/sykehusprofil/index.tsx#L89-L106

**Comment by jo-inge-arnes** [comment]
Spørs hva som skal gjøres. Dette er en callback-funksjon som kalles når brukeren velger noe nytt. Man kan også definere en callback-funksjon som kalles i forbindelse med at de initielle filterverdiene er satt. Best at vi tar en kikk på dette sammen og at du forklarer casen :)

**Comment by jo-inge-arnes** [comment]
Det henger sammen med query-parameter og prerendring i Next.js. Man kan sjekke om query-parameterne er klare, som vist under, og sette shouldRefreshInitialState.

/////////////

  // When the user navigates to the page, it may contain query parameters for
  // filtering indicators. Use NextRouter to get the current path containing the
  // initial query parameters.

  const router = useRouter();

  // Next's prerender stage causes problems for the initial values given to
  // useReducer, because they are only set once by the reducer and are missing
  // during Next's prerender stage. Tell FilterMenu to refresh its state during
  // the first call after the prerender is done.

  const [prevReady, setPrevReady] = useState(router.isReady);

  const prerenderFinished = prevReady !== router.isReady;

  useEffect(() => {
    setPrevReady(router.isReady);
  }, [router.isReady]);


  const shouldRefreshInitialState = prerenderFinished;

/////////////

**Comment by jo-inge-arnes** [comment]
Merk at nodene i treet skal ekspanderes automatisk for å vise den valgte enheten, men dette virker ikke lenger. Dette er en annen bug som jeg tror kan skyldes oppgradering fra mui/x-tree-view v6 til v7
